# Site settings
title: SYF Blog
header-img: img/home-bg.jpg
email: yunfeishi7@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/SYF"
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  mangogoing
facebook_username:  IronSummitMedia
email_username:  yunfeishi7@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
#keep_files: ["_includes","_layouts","_posts"]
#include: ["_includes","_layouts","_posts","css","fonts","img","js","mail"]

gems: [jekyll-paginate, jekyll-feed]

